# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import webbrowser
from PyQt5 import QtCore, QtWidgets
import re, requests as rq
from getmac import get_mac_address
from PyQt5.QtCore import QTimer
from datetime import datetime

SIGNINSRVR = 'http://elton-m1.local:4000/'

class MainWindow (QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.timer = QTimer(self)
        self.timer.timeout.connect(self.timer_event)
        self.timer.start(300000)    
        self.bYetLogIn = True
    def timer_event(self):
        if self.bYetLogIn:
            self.showMaximized()
        else:
            t = datetime.now().time()
            if (t.hour > 15 and 15 < t.minute < 21) or 5 < t.minute < 11: # short circuit evaluation
                self.bYetLogIn = True
                # Todo: relayout for login + test timer accuracy
                self.showMaximized()
    def closeEvent(self, event):
        event.ignore()
        
class Ui_HuangTech(object):
    
    def setupUi(self, HuangTech):
        HuangTech.setObjectName("HuangTech")
        HuangTech.resize(270, 256)
        self.centralwidget = QtWidgets.QWidget(HuangTech)
        self.centralwidget.setObjectName("centralwidget")
        self.clr = QtWidgets.QPushButton(self.centralwidget)
        self.clr.setGeometry(QtCore.QRect(20, 180, 113, 32))
        self.clr.setObjectName("clr")
        self.chklogin = QtWidgets.QPushButton(self.centralwidget)
        self.chklogin.setGeometry(QtCore.QRect(140, 180, 113, 32))
        self.chklogin.setObjectName("chklogin")
        self.pw = QtWidgets.QLineEdit(self.centralwidget)
        self.pw.setGeometry(QtCore.QRect(70, 140, 113, 21))
        self.pw.setObjectName("pw")
        self.pw_label = QtWidgets.QLabel(self.centralwidget)
        self.pw_label.setGeometry(QtCore.QRect(70, 120, 81, 16))
        self.pw_label.setObjectName("pw_label")
        self.id = QtWidgets.QLineEdit(self.centralwidget)
        self.id.setGeometry(QtCore.QRect(70, 80, 113, 21))
        self.id.setObjectName("id")
        self.id_label = QtWidgets.QLabel(self.centralwidget)
        self.id_label.setGeometry(QtCore.QRect(70, 60, 121, 16))
        self.id_label.setObjectName("id_label")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(70, 20, 131, 31))
        self.title.setObjectName("title")
        HuangTech.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(HuangTech)
        self.statusbar.setObjectName("statusbar")
        HuangTech.setStatusBar(self.statusbar)
        
        self.retranslateUi(HuangTech)
        QtCore.QMetaObject.connectSlotsByName(HuangTech)

        self.bYetLogin = True
        self.clr.clicked.connect      (self.clear)
        self.chklogin.clicked.connect (self.checklogin)
        self.pw.returnPressed.connect (self.checklogin)
        self.id.returnPressed.connect (self.identer)
        self.id.setFocus()

    def retranslateUi(self, HuangTech):
        _translate = QtCore.QCoreApplication.translate
        HuangTech.setWindowTitle(_translate("HuangTech", "黃老師科技課程登入"))
        self.clr.setText(_translate("HuangTech", "清除"))
        self.chklogin.setText(_translate("HuangTech", "查詢"))
        self.pw_label.setText(_translate("HuangTech", "學號末 4 碼"))
        self.id_label.setText(_translate("HuangTech", "班級座號 (共 5 碼)"))
        self.title.setText(_translate("HuangTech", "<html><head/><body><p><span style=\" font-size:18pt;\">黃老師科技課程</span></p></body></html>"))

    def checklogin (self):
        if self.chkid():
            resp = rq.post (SIGNINSRVR + 'login', json = {'username':self.id.text(), 'password':self.pw.text(), 'mac':get_mac_address() })
            if resp.status_code == 200:
                _translate = QtCore.QCoreApplication.translate
                self.pw_label.setText(_translate("HuangTech", "姓名"))
                self.layout.replaceWidget(self.pw, label)
                webbrowser.open (SIGNINSRVR + 'answers')
            else:
                self.statusbar.showMessage ('請通知老師：連不上伺服器！')
        else:
            self.statusbar.showMessage ('班級座號錯誤')
            self.id.setFocus()
            
    def chkid (self):
        # if self.bYetLogin:
        if re.match ('^[1-3][0-9][0-9][0-4][0-9]$', self.id.text()):
            self.statusbar.clearMessage ()
            return True
        else:
            self.statusbar.showMessage ('班級座號錯誤')
            return False
            
    def identer (self):
        if self.chkid():
            self.pw.setFocus()
    
    def clear (self):
        self.pw.clear()
        self.id.clear()
        self.id.setFocus()
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HuangTech = MainWindow()
    ui = Ui_HuangTech()
    ui.setupUi(HuangTech)
    HuangTech.show()
    sys.exit(app.exec_())
