# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signin2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(285, 252)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.login_wgt = QtWidgets.QWidget(self.centralwidget)
        self.login_wgt.setGeometry(QtCore.QRect(20, 20, 241, 201))
        self.login_wgt.setObjectName("login_wgt")
        self.id_label = QtWidgets.QLabel(self.login_wgt)
        self.id_label.setGeometry(QtCore.QRect(50, 50, 121, 16))
        self.id_label.setObjectName("id_label")
        self.title = QtWidgets.QLabel(self.login_wgt)
        self.title.setGeometry(QtCore.QRect(50, 0, 131, 31))
        self.title.setObjectName("title")
        self.pw = QtWidgets.QLineEdit(self.login_wgt)
        self.pw.setGeometry(QtCore.QRect(50, 130, 113, 21))
        self.pw.setObjectName("pw")
        self.clr = QtWidgets.QPushButton(self.login_wgt)
        self.clr.setGeometry(QtCore.QRect(0, 170, 113, 32))
        self.clr.setObjectName("clr")
        self.pw_label = QtWidgets.QLabel(self.login_wgt)
        self.pw_label.setGeometry(QtCore.QRect(50, 110, 81, 16))
        self.pw_label.setObjectName("pw_label")
        self.id = QtWidgets.QLineEdit(self.login_wgt)
        self.id.setGeometry(QtCore.QRect(50, 70, 113, 21))
        self.id.setObjectName("id")
        self.login = QtWidgets.QPushButton(self.login_wgt)
        self.login.setGeometry(QtCore.QRect(120, 170, 113, 32))
        self.login.setObjectName("login")

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.id_label.setText(_translate("MainWindow", "班級座號 (共 5 碼)"))
        self.title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">黃老師科技課程</span></p></body></html>"))
        self.clr.setText(_translate("MainWindow", "清除"))
        self.pw_label.setText(_translate("MainWindow", "學號末 4 碼"))
        self.login.setText(_translate("MainWindow", "登入"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
