# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HuangTech(object):
    def setupUi(self, HuangTech):
        HuangTech.setObjectName("HuangTech")
        HuangTech.resize(328, 294)
        self.centralwidget = QtWidgets.QWidget(HuangTech)
        self.centralwidget.setObjectName("centralwidget")
        self.clr = QtWidgets.QPushButton(self.centralwidget)
        self.clr.setGeometry(QtCore.QRect(50, 230, 113, 32))
        self.clr.setObjectName("clr")
        self.chklogin = QtWidgets.QPushButton(self.centralwidget)
        self.chklogin.setGeometry(QtCore.QRect(160, 230, 113, 32))
        self.chklogin.setObjectName("chklogin")
        self.stuname = QtWidgets.QLabel(self.centralwidget)
        self.stuname.setGeometry(QtCore.QRect(100, 200, 141, 16))
        self.stuname.setText("")
        self.stuname.setObjectName("stuname")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(100, 180, 60, 16))
        self.name.setText("")
        self.name.setObjectName("name")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 140, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pw = QtWidgets.QLabel(self.centralwidget)
        self.pw.setGeometry(QtCore.QRect(100, 120, 81, 16))
        self.pw.setObjectName("pw")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 80, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.id = QtWidgets.QLabel(self.centralwidget)
        self.id.setGeometry(QtCore.QRect(100, 60, 121, 16))
        self.id.setObjectName("id")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(100, 10, 131, 31))
        self.title.setObjectName("title")
        HuangTech.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(HuangTech)
        self.statusbar.setObjectName("statusbar")
        HuangTech.setStatusBar(self.statusbar)

        self.retranslateUi(HuangTech)
        QtCore.QMetaObject.connectSlotsByName(HuangTech)

    def retranslateUi(self, HuangTech):
        _translate = QtCore.QCoreApplication.translate
        HuangTech.setWindowTitle(_translate("HuangTech", "黃老師科技課程登入"))
        self.clr.setText(_translate("HuangTech", "清除"))
        self.chklogin.setText(_translate("HuangTech", "查詢"))
        self.pw.setText(_translate("HuangTech", "學號末 4 碼"))
        self.id.setText(_translate("HuangTech", "班級座號 (共 5 碼)"))
        self.title.setText(_translate("HuangTech", "<html><head/><body><p><span style=\" font-size:18pt;\">黃老師科技課程</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HuangTech = QtWidgets.QMainWindow()
    ui = Ui_HuangTech()
    ui.setupUi(HuangTech)
    ui.chklogin.clicked.connect (chklogin)
    ui.pw.returnPressed.connect (chklogin)
    HuangTech.show()
    sys.exit(app.exec_())
