# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'signin1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import re, requests as rq, webbrowser, on_wgt, login_wgt
from getmac import get_mac_address
from PyQt5.QtCore import QTimer
from datetime import datetime

SIGNINSRVR = 'http://elton-m1.local:4000/'

class MainWindow (QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.timer = QTimer(self)
        self.timer.timeout.connect(self.timer_event)
        self.timer.start(300000)    
        self.bYetLogIn = True
    def timer_event(self):
        if self.bYetLogIn:
            self.showMaximized()
        else:
            t = datetime.now().time()
            if (t.hour > 15 and t.minute > 10 and 15 < t.minute < 21) or 5 < t.minute < 11: # short circuit evaluation
                self.bYetLogIn = True
                # Todo: relayout for login + test timer accuracy
                self.showMaximized()
    def closeEvent(self, event):
        event.ignore()
        
class Ui_HuangTech(object):
    
    def setupUi(self, HuangTech):
        HuangTech.setObjectName("HuangTech")
        HuangTech.resize(270, 256)
        self.centralwidget = QtWidgets.QWidget(HuangTech)
        self.centralwidget.setObjectName("centralwidget")
        HuangTech.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(HuangTech)
        self.statusbar.setObjectName("statusbar")
        HuangTech.setStatusBar(self.statusbar)

        self.retranslateUi(HuangTech)
        QtCore.QMetaObject.connectSlotsByName(HuangTech)

    def retranslateUi(self, HuangTech):
        _translate = QtCore.QCoreApplication.translate
        HuangTech.setWindowTitle(_translate("HuangTech", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HuangTech = QtWidgets.QMainWindow()
    ui = Ui_HuangTech()
    ui.setupUi(HuangTech)
    HuangTech.show()
    sys.exit(app.exec_())
